// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Onb6JPDY05oUU5ArfxX5z4RtnJrUsTo',
    appId: '1:532987756525:web:86d0e540383679fe4031e4',
    messagingSenderId: '532987756525',
    projectId: 'explore-ease-171d1',
    authDomain: 'explore-ease-171d1.firebaseapp.com',
    storageBucket: 'explore-ease-171d1.firebasestorage.app',
    measurementId: 'G-WVSL91HXPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDar6NsnnU35iVb01zmaF79ATqiDobF4D4',
    appId: '1:532987756525:android:cdec1d5175847d104031e4',
    messagingSenderId: '532987756525',
    projectId: 'explore-ease-171d1',
    storageBucket: 'explore-ease-171d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuG0tTdWP7rXrK0RfQ4pSrABC1RdcUT4Q',
    appId: '1:532987756525:ios:e2ce32757ae5db824031e4',
    messagingSenderId: '532987756525',
    projectId: 'explore-ease-171d1',
    storageBucket: 'explore-ease-171d1.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuG0tTdWP7rXrK0RfQ4pSrABC1RdcUT4Q',
    appId: '1:532987756525:ios:e2ce32757ae5db824031e4',
    messagingSenderId: '532987756525',
    projectId: 'explore-ease-171d1',
    storageBucket: 'explore-ease-171d1.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Onb6JPDY05oUU5ArfxX5z4RtnJrUsTo',
    appId: '1:532987756525:web:256d7ceeb1ab07aa4031e4',
    messagingSenderId: '532987756525',
    projectId: 'explore-ease-171d1',
    authDomain: 'explore-ease-171d1.firebaseapp.com',
    storageBucket: 'explore-ease-171d1.firebasestorage.app',
    measurementId: 'G-703GD2X1DT',
  );
}
